- name: Развертывание ARKANA PULSE
  hosts: localhost
  tasks:
    # - name: 1. Клонируем репозиторий проекта
    #   git:
    #     repo: 'https://github.com/REkito5201/Arkana-Pulse.git'
    #     dest: /home/rekito5201/Arkana-Pulse

    - name: 2. Создаем .env файл из шаблона
      copy:
        src: /home/rekito5201/Arkana-Pulse/.env.example
        dest: /home/rekito5201/Arkana-Pulse/.env
        remote_src: yes

    - name: 3. Поднимаем стек через Docker Compose
      command: docker compose up -d --build
      args:
        chdir: /home/rekito5201/Arkana-Pulse
